name: Docker Publish

on:
  push:
    branches:
      - add-docker-build-action

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish Docker image
        working-directory: Pappion.API
        run: |
          docker build . --file Dockerfile --tag pappion:$(date +%s)
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pappion:${{ github.sha }}
